server:
  port: 8080

info:
  name: Api Gateway
  version: ${version}

zuul:
  prefix: /api
  routes:
    car-manager:
      path: /v1/car-manager/**
      service-id: car-manager
  ignored-services: '*'